### PR TITLE
Swap AWX logos

### PR DESCRIPTION
**Pull request by mabashian**
Swap em

### CODE REVIEW

**Comment by idawko** [comment]
Would you mind explaining why did you swap the logos to empty SVGs?

**Comment by ryanpetrello** [comment]
Hey @idawko,

I've got some information about this forthcoming this week.  I'll post an update here.

**Comment by ryanpetrello** [comment]
@idawko: https://groups.google.com/g/awx-project/c/4gCe1NSVuu4

**Comment by idawko** [comment]
@ryanpetrello I appreciate your answer.

**Pull request merged**
